### ISSUE TITLE
Before Tuesday 12:00: vote on time, date, frequency, location

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#10]
After #2, this is the Issue to vote on the suggestions. 

 * I will put the suggestions here at ~~Friday~~ Monday between ~~12:00-13:00~~ 8:30-8:45 **[edit: was ill, so moved day and time]** 
 * Voting until ~~Monday~~ Tuesday 12:00. At 12:00 the suggestion with most votes will be it. If there is only one suggestion, it will be that one :+1: **[edit: was ill, so moved day]**

**Comment by richelbilderbeek** [comment]
These are the options:

 * Before each Keivrijdag (that is, once per two weeks), from 17:00-19:00 at Franjo's fancy library (580) in the Linnaeusborg.
 *  Weekly, Thursdays 17:00-19:00
 *  Every two weeks, Thursdays 17:00-19:00

**Comment by richelbilderbeek** [comment]
Timespan and interval|Yes/no
---|---
Before each Keivrijdag, from 17:00-19:00|Yes
Weekly, Thursdays 17:00-19:00|No
Every two weeks, Thursdays 17:00-19:00|No

**Comment by Xiaoyan2** [comment]
> Timespan and interval	Yes/no
> Before each Keivrijdag, from 17:00-19:00	No
> Weekly, Thursdays 17:00-19:00	No
> Every two weeks, Thursdays 17:00-19:00	Yes

**Comment by Neves-P** [comment]
Timespan and interval|Yes/no
---|---
Before each Keivrijdag, from 17:00-19:00|Yes
Weekly, Thursdays 17:00-19:00|No
Every two weeks, Thursdays 17:00-19:00|No

**Comment by swom** [comment]
Timespan and interval | Yes/no
-- | --
Before each Keivrijdag, from 17:00-19:00 | Yes
Weekly, Thursdays 17:00-19:00 | No
Every two weeks, Thursdays 17:00-19:00 | Possible secondary date in case Friday is not possible

**Comment by marinapapa** [comment]
Yes - Yes - Yes
