### ISSUE TITLE
Test 'menu_view' on Travis

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#105]
I see [the code coverage of menu_view is zero percent](https://codecov.io/gh/tresinformal/game/src/richel/menu_view.cpp).

This is completely logical: the menu is not tested on Travis.

Modify the `.travis.yml` script to also show the menu on Travis, so we can get some code coverage on the `menu_view` class.

**Comment by swom** [comment]
Richel, I do not get how to solve this problem. 
When I run the command `$ ./game --menu` or even just `$ ./game`
[Travis ](https://travis-ci.org/tresinformal/game/builds/621695442)gives me this error:
`X Error of failed request:  BadAtom (invalid Atom parameter)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Atom id in failed request:  0xec
  Serial number of failed request:  44
  Current serial number in output stream:  53
The command "./game " exited with 1.`.
I tried to see google what the error is about but it is pretty hard to figure out on my own, it seems it is related to the fact that by running the game and not only its tests(as with '$./game test')I try to access something I am not allowed/cannot access on Travis and therefore the error is thrown. In my opinion I think this has to do with trying to open a RenderWindow on Travis. I tried a couple of solutions but could not make it work. Do you have any suggestions?

**Comment by richelbilderbeek** [comment]
@swom: Hmmm, I only have one vague idea. As far as I remember, there can only by one sf::RenderWindow active. That is why [Nature Zen](https://github.com/richelbilderbeek/djog_unos_2018) had a window manager.

I'll take a look today. tomorrow or Wednesday :+1:

**Comment by richelbilderbeek** [comment]
I unpinned the Issue: (1) there still is plenty of other things to do, (2) I will take a look on Saturday :+1:

**Comment by richelbilderbeek** [comment]
This madness must stop now(at least until [https://travis-ci.community/t/unable-to-locate-package-devscriptsgfortran-on-bionic/6445] is fixed :grin:) !

**Comment by richelbilderbeek** [comment]
I give up for now.

The reason why this is so hard, is -AFAICS- that `xvfb` needs to be restarted per process. But I may completely misunderstand. 

As a workaround:

 * The game logic is completely tested
 * Only the game's main screen is run on Travis

**Comment by swom** [comment]
Thanks Richel

**Comment by richelbilderbeek** [comment]
Yup, time to move on :rainbow:
