### ISSUE TITLE
Think of sound effects we need.

### ISSUE THREAD

**Issue by sebmader** [tresinformal/game#107]
There are multiple events/situations we need sounds for.
Comment this issue with your suggestions and ideas.

Examples:
    - eat something
    - hit a boundary

**Comment by Neves-P** [comment]
Ideas for effects:

- Get eaten
- Enter camouflage area
- When shooting
- Get power-up

**Comment by richelbilderbeek** [comment]
I feel this Issue has gone stale.

I suggest to close this Issue and add sound effects on the go with or without adding the suggestions to `sound_type`

**Comment by sebmader** [comment]
Agree.

**Comment by richelbilderbeek** [comment]
Cool, will close this Issue :+1:

**Comment by TheoPannetier** [comment]
@sebmader I see this issue is tagged as Done, should it be closed or are you still working on it?

**Comment by richelbilderbeek** [comment]
Time to close it, it seems to me. I will ruthlessly do so now :-)
