### ISSUE TITLE
Think of situations we need a different soundtrack for.

### ISSUE THREAD

**Issue by sebmader** [tresinformal/game#108]
We will need multiple background soundtracks for different situations. What are these situations?
Comment this issue with ideas and suggestions.

Example:
    - Menu music
    - No danger
    - Danger

**Comment by Neves-P** [comment]
Situations for different background soundtracks:
- You lose screen
- Credits screen

**Comment by richelbilderbeek** [comment]
This Issue is Done for 4 months. I will ruthlessly Close it :-)
