### ISSUE TITLE
Players can eat each other

### ISSUE THREAD

**Issue by swom** [tresinformal/game#127]
- [x] Contact between players is handled
- [x] Depending on color and size one players get to eat the other
- [ ] The other player gets destroyed and recreated at a random location

Tests:
- A test that ensures that some flag is activated when players overlap
- A test that ensures that after having evaluated players the right to eat is given to one or none
- A test that ensures that once a player is eaten that player is not on the map anymore
- A test that ensures that after a certain time a player that is not on the map is respawned

**Comment by richelbilderbeek** [comment]
I will take over today :sunglasses:

**Comment by richelbilderbeek** [comment]
I will close this one for now: it has gone stale. There will be a new fresh Issue :+1:
