### ISSUE TITLE
Upon collision, the redder Franjo wins while the other Franjo disappears

### ISSUE THREAD

**Issue by AparajithaRamesh** [tresinformal/game#134]
Now, the Franjo that initiates collision disappears. Adding condition that upon collision, the one that is redder wins and the other disappears

**Comment by AparajithaRamesh** [comment]
Rock paper scissor dynamics: red defeats green, green defeats blue and blue defeats red!!

**Comment by richelbilderbeek** [comment]
AFAICS: done!
