### ISSUE TITLE
Add new weapon key

### ISSUE THREAD

**Issue by GiorgioBoccarella** [tresinformal/game#144]
Add new weapon key, E shoots different projectile

**Comment by GiorgioBoccarella** [comment]
Added food_type first

**Comment by richelbilderbeek** [comment]
We will take over from here :+1:

**Comment by richelbilderbeek** [comment]
This will be the same key as https://github.com/tresinformal/game/issues/239 .

**Comment by TheoPannetier** [comment]
Has this been superseded by #239?
Let's close it then?

**Comment by TheoPannetier** [comment]
Housekeeping 🧹
I'll close this for now as it seems to be no longer relevant. Re-open if I'm wrong!
