### ISSUE TITLE
Meeting 2019-09-27

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#15]
Timespan|What
---|---
17:00-17:bb|Suggest to do 3 mins per *suggestion*
17:bb-17:xx|Final collection of suggestions for game (from #3 and #12), 3 mins max per person
17:xx-17:yy|Vote on game
17:yy-17:zz|Collect suggestions for library (from #13), 3 mins max per person
17:zz-17:aa|Vote on graphics library

These are the ideas so far:

 * Bird nest defense and reproduction game, with evolution in it!
 * Phd Game
 * The useless game
 * Limited resources mechanic
 * 2D PvP chasing game, +1 by Apu
 * Defense game, Guards vs. Thieves
 * Turn based brawler/extreme-volleyball game.

## Notes

 * `xx` can denote any number from `0` to and including `59`.

**Comment by AparajithaRamesh** [comment]
I'm not able to join for today's meeting as I am taking driving lessons  like a maniac, trying to get a Dutch driving licence and it happens to fall during this time slot. I would like to cast my vote already based on the description of these games. I like the **2D PvP chasing game**  !!!

**Comment by richelbilderbeek** [comment]
Vote in noted!

**Comment by richelbilderbeek** [comment]
Note: you can vote multiple times!

**Comment by richelbilderbeek** [comment]
Game we chose:

```
2D PvP chasing game
```
