### ISSUE TITLE
Design a better background

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#151]
Currently, the background is all blocky.

Goal of the background is to have spots where a certain color is more camouflaged.

My personal idea would be to make sine-like patches of red green and blue, something like:

![wave_surface](https://user-images.githubusercontent.com/2098230/77188984-26d18680-6ad7-11ea-8c9d-86ccac3e38da.png)

Or this one:

![landscape](https://user-images.githubusercontent.com/2098230/109827910-718ed480-7c3c-11eb-9b48-b19a89887f42.png)

Yet, you can ignore that for your own superior idea! All it needs to be is heterogeneous and help the player be camouflaged in any way.

**Comment by TheoPannetier** [comment]
@inesdaras, how's your progress with this? Are you keeping the idea of camouflaged players as in the description?
I think this issue and #153 should be addressed together, let's discuss the artistic direction some time 🧑‍🎨

**Comment by TheoPannetier** [comment]
spotted this today:
https://www.data-imaginist.com/2020/a-noisy-start/

It's for R, but maybe that could be used to generate a static picture for the bakground?

**Comment by inesdaras** [comment]
Oh wow, it looks cool...I will have a better look by Wednesday!
I was thinking of something trashy, like a flower-background...
Petals have one of the three payers' colors (drawn as somewhat small
circles, but big enough to fully camouflage one player), while the center
of the flower is a large circle which changes color in time, such that each
player can receive a camouflage advantage periodically.
Or something like it, still I have no clue on whether this is feasible ahah
Talk Wednesday!

**Comment by TheoPannetier** [comment]
We have a better background now
