### ISSUE TITLE
Travis does not check my commits

### ISSUE THREAD

**Issue by swom** [tresinformal/game#154]
@richelbilderbeek I am having trouble with Travis, who does not see my commits any more? Do you have an idea why? It seems to me I am signed in in GitHub also in Git Bash. I think it has to do with me fiiddeling with my credential in Git Bash.

**Comment by richelbilderbeek** [comment]
Fun! I'll taka a look :+1:

**Comment by richelbilderbeek** [comment]
Note to self:

```
richel@sonic:~/GitHubs/game$ git pull
Updating ae49217..62b6bb9
Fast-forward
 game.cpp                   |  10 ++--
 game.h                     |  10 +++-
 game.pro                   |   6 +-
 game_view.cpp              | 286 ++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------
 game_view.h                |  18 ++++++
 main.cpp                   |   2 +-
 menu.cpp                   |  68 ++++++++++++++++++++++
 menu_logic.h => menu.h     |  10 ++--
 menu_logic.cpp             |  73 -----------------------
 menu_view.cpp              |  12 ++--
 menu_view.h                |   4 +-
 program_state.cpp          |  37 ++++++++++++
 program_state.h            |  18 ++++++
```

All, normal, then:

```
 "\357\200\233\357\200\233" | 158 ++++++++++++++++++++++++++++++++++++++++++++++++++
 14 files changed, 503 insertions(+), 209 deletions(-)
 create mode 100644 menu.cpp
 rename menu_logic.h => menu.h (88%)
 delete mode 100644 menu_logic.cpp
 create mode 100644 program_state.cpp
 create mode 100644 program_state.h
 create mode 100644 "\357\200\233\357\200\233"
```

What kind of file is it:

richel@sonic:~/GitHubs/game$ ls
                    food_type.cpp               main.cpp                                             player_sprite.png
```

Can't show here, here is a picture:

![screen](https://user-images.githubusercontent.com/2098230/77226914-32c35400-6b7c-11ea-8b86-b5a0f3869797.png)

Rest is just normal:

```
action_type.cpp       food_type.h                 Makefile                                             program_state.cpp
action_type.h         franjo.png                  Makefile.Debug                                       program_state.h
bump.ogg              franjo_rotated.png          Makefile.Release                                     projectile.cpp
cat.png               game                        menu_button.cpp                                      projectile.h
CMakeLists.txt        game.cpp                    menu_button.h                                        projectile_type.cpp
color.cpp             game.h                      menu.cpp                                             projectile_type.h
color.h               game_options.cpp            menu.h                                               README.md
correct_code          game_options.h              menu_view.cpp                                        release
current_code          game.pro                    menu_view.h                                          rocket_sprite.png
enemy.cpp             game.pro.user               ninja_gods.ogg                                       scripts
enemy.h               game_resources.cpp          oclint-0.10.3                                        shelter.cpp
environment.cpp       game_resources.h            oclint-0.10.3-x86_64-linux-3.13.0-74-generic.tar.gz  shelter.h
environment.h         game_resources.qrc          oclint.log                                           shoot.ogg
environment_type.cpp  game_view.cpp               pics                                                 sound_type.cpp
environment_type.h    game_view.h                 player.cpp                                           sound_type.h
fairytale.md          grass_landscape.png         player.h                                             wonderland.ogg
food.cpp              heterogenous_landscape.jpg  player_shape.cpp
food.h                LICENSE                     player_shape.h
richel@sonic:~/GitHubs/game$ 
```

Hypothesis: weird file messes things up...

**Comment by richelbilderbeek** [comment]
Note to self: [build just passed](https://travis-ci.org/github/tresinformal/game/builds/665157585#L3940), problem solved?

**Comment by richelbilderbeek** [comment]
@swom: I see your build has just passed. Does that mean the problem is fixed?
