### ISSUE TITLE
[recurring] Install Qt Creator and SFML

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#16]
To develop for the game, one needs Qt Creator. Qt Creator is an IDE, which is powerful, cross-platform and is free for FOSS development. Also, we use the `qmake` build system (you can use other IDE's, such as Visual Studio, but then I cannot help you how to get it working)

To run our game, we need to have SFML installed. SFML is a graphics library that is powerful, easy (enough) to use and FOSS.

Install instructions found [here](https://github.com/tresinformal/game/blob/master/install.md).

As always, assign yourself when doing this Issue, unassign upon completion.

As this Issue is 'Recurring', this means that:

 * If you want to do this Issue and it is closed: re-open it
 * If there are no assignees left: close it

**Comment by richelbilderbeek** [comment]
Unassign when you did this :rainbow: :+1: 

You may send me an email if you fail somehow.

**Comment by TheoPannetier** [comment]
Done!

**Comment by kausmees** [comment]
Done!

**Comment by richelbilderbeek** [comment]
@Tingvall: I think you are done here? If yes, please Unassign :innocent:

**Comment by TheoPannetier** [comment]
Done with this issue :)

**Comment by mrcoolepicman** [comment]
Done. :))))))))))))))))))))))))))))))))))))))))
