### ISSUE TITLE
Display first player's coordinates in empty space

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#167]
Currently, at the top-right, there is only black:

![screen](https://user-images.githubusercontent.com/2098230/79575356-efe49580-80c1-11ea-84f3-afe73265d6b8.png)

That black square is great for adding debug info!

To get started, display the first player's coordinats there. Text should be:

```
1: (x, y)
```

where `x` and `y` are the coordinats.

If you prefer, you may round off the coordinats and/or display the other players as well.

**Comment by TheoPannetier** [comment]
- [ ] Display first player coordinates anywhere on screen, e.g close to (0, 0)
- [ ] Extend to all three players
- [ ] Set the fourth view screen to an area outside of the environment (and out of players sight)
- [ ] Move text inside the view of the fourth screen
