### ISSUE TITLE
Change signature of 'to_str_program_state'

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#169]
Currently, we have a function like this:

```c++
const std::string to_str_program_state(program_state this_program_state);
```

Problems are:

 * Never return a value by const-copy, so use `string` instead of `const string`
 * C++ is type safe, so `to_str_program_state(program_state)` is a pleonasm. Use `to_str(program_state)` instead
 * The `program_state` is an input that is only read, thus use `const program_state this_program_state` as the function's argument
 * From a valid `program_state`, there is always a valid string possible, so add `noexcept` at the end of the function

Make it so. Take 15 minutes at most to read up a bit on this if needed. Else, there is a spoiler below how the function should be.

0
9
8
7
6
5
4
3
2
1
0
9
8
7
6
5
4
3
2
1
0
9
8
7
6
5
4
3
2
1

```c++
std::string to_str(const program_state this_program_state) noexcept;
```

**Comment by inesdaras** [comment]
Closed because already done!
