### ISSUE TITLE
Suggest game mechanics

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#17]
In the README is a description of the game. Suggest your wacky game mechanics her. No worries if it's too weird: when in doubt, we follow the Ruthless Democracy rules :+1:

**Comment by richelbilderbeek** [comment]
Thanks @joshwlambert:

Character appearance:
(1) rocket
(2) circle
(3) user specified shape 
(5) peoples (our) faces

Environment:
(1) Empty environment
(2) Static food 
(3) Dynamic food:
(a) random movement
(b) attractive within a given proximity (gravity-like)
(c) repellent within a given proximity 
(4) computer controlled opponents
(5) wormhole to move to another part of the map
(6) 
Ability of character:
(1) grow in size when attaining food
(2) attain attributes (i.e. ability to shoot)
(3) change form (e.g. change between a moving and consuming form)
(4) Absorb certain object and gain a special ability (e.g. to shoot)
(5) Degradation of character when hit with certain objects
(6) teleport to another part of the map

Type of food:
(1) Rockets and laser, when rockets are absorbed you gain the ability to shoot
(2) particles, when certain particles are absorbed you form a new molecule and gain the 
characteristics of these molecules
(3) plain shapes

Ways to defeat the opponent:
(1) eat them when you attain a critical size
(2) eat them when you are bigger than them by a given ratio
(3) shoot them once
(4) reduce their health to zero
(5) reach a certain part of the map
(6)

**Comment by richelbilderbeek** [comment]
I suggest that a player has to specialize in a color vision, like cichlids!

A player can develop a color like R/G/B and develop a vision seeing R/G/B best

**Comment by AparajithaRamesh** [comment]
Idea: Some rare 'bonus' food items can help you blend into the 'heterogeneous surrounding' for a particular amount of time, making it hard for other players to see you. Time for sneak attack!

**Comment by richelbilderbeek** [comment]
Enough game mechanics for now, now we move on a day-by-day basis. Closing this one :+1:
