### ISSUE TITLE
Use std::map in key_action_map

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#175]
Currently, `key_action_map` is completely handcrafted, as can be shown by its private section:

```c++
class key_action_map
{
  // ...
private:
  sf::Keyboard::Key m_key_to_go_left;
  sf::Keyboard::Key m_key_to_go_right;
  sf::Keyboard::Key m_key_to_accelerate;
  sf::Keyboard::Key m_key_to_brake;
  sf::Keyboard::Key m_key_to_shoot;
};

It is preferable to use STL classes if possible. And (as the name already implies) we can use `std::map` to do the heavy lifting for us!

After reading up on `std::map`, replace the private member variables by using a `std::map`, as shown below (I leave the template types as an exercise as well):

```c++
class key_action_map
{
  // ...
private:
  std::map<..., ...> m_map;
};
```

After doing so, all tests should remain passing.

**Comment by janclod** [comment]
I have implemented an std::map but I had to remove const in several places. Somehow it feels a wrong and scary to do. In any case the code runs and passes all tests.

**Comment by janclod** [comment]
Not only removed this special word in the key_action_map files also in the game_view.cpp file.

**Comment by janclod** [comment]
Indded there are some more problems that arise from this. Will have to work more on this next time...
