### ISSUE TITLE
Remove non-const game::get_n_ticks

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#177]
Currently, `game` has a public member function to allow any caller to change the number of ticks it has had:

```
  /// Gets reference adress of number of ticks
  int &get_n_ticks() noexcept { return m_n_ticks; }
```

Although this was probably well intended, this is a bad idea: only `game` should be able to change the number of ticks it has had.

Remove this member function and make the code compile again.

**Comment by TheoPannetier** [comment]
Brilliant, I was just looking for an issue to practice wroking with classes 😁

**Comment by TheoPannetier** [comment]
Fixed 🥇
