### ISSUE TITLE
Compile in release mode must be silent

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#190]
When the game is compiled in release, there are multiple compiler warnings, such as [these](https://travis-ci.org/github/tresinformal/game/builds/690103731#L1520):

```
ame.cpp: In function ‘void test_game()’:
game.cpp:388:22: warning: unused variable ‘before’ [-Wunused-variable]
game.cpp:390:22: warning: unused variable ‘after’ [-Wunused-variable]
game.cpp:399:22: warning: unused variable ‘before’ [-Wunused-variable]
[...]
```

These 'unused' variables are unused, because in release mode, all `assert`s are removed. Therefore, all what is left, are some variables.

The way to fix this, is to remove the tests, using an `#ifdef` on `NDEBUG`, such as:

```
#ifndef NDEBUG
//  tests here
#endif
```

Put all tests in these `#ifndef`s. If there are unused variables elsewhere, ignore these for now.

**Comment by TheoPannetier** [comment]
Done!
