### ISSUE TITLE
Test player::acc_backward

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#193]
Currently, the `player::acc_backward` looks suspicious: it has one `if` statement that in both cases does the same:

```c++
void player::acc_backward() noexcept
{
    if (m_player_speed < -m_player_max_speed)
    {
        m_player_speed = -m_player_max_speed;
    }
    else
    {
        m_player_speed = -m_player_max_speed;
    }
    // ...
}
```

Write a test to check that `acc_backward` does the right thing.

**Comment by sebmader** [comment]
@richelbilderbeek
Can you maybe check the tests that I wrote, and if they make sense?
If I run them they fail, but fixing that should be a new issue, I feel.
Find them with searching for FIX_ISSUE_193 (I stuck to the number of this issue).

**Comment by richelbilderbeek** [comment]
I will check your work of art before next meeting  :+1:

**Comment by sebmader** [comment]
No stress :)

**Comment by richelbilderbeek** [comment]
I checked your work. Well done! I pushed my feedback on your branch, it is to focus more on what backwards acceleration does, i.e. actually go backwards :-)

**Comment by sebmader** [comment]
Richel implemented new tests to make sure, backwards acceleration ACTUALLY makes the player go backwards:
```
//#define FIX_ISSUE_193
#ifdef FIX_ISSUE_193
  // RJCB: my suggested test
  // A players goes ?right/?up upon acceleraton
  {
      player p_forward;
      p_forward.accelerate();
      assert(get_dx(p_forward) > 0.0); // Get the delta x, maybe needs to be added
      assert(get_dy(p_forward) > 0.0); // Get the delta x, maybe needs to be added
      player p_backward;
      p_backward.acc_backward();
      assert(get_dx(p_backward) < 0.0); // Signs should flip
      assert(get_dy(p_backward) < 0.0); // Signs should flip
  }
  // RJCB: another suggested test
  // A players actually goes backwards after some backwards accelerations
  {
      player p;
      p.accelerate();
      assert(get_dx(p) > 0.0); // Get the delta x, maybe needs to be added
      assert(get_dy(p) > 0.0); // Get the delta x, maybe needs to be added
      p.acc_backward();
      p.acc_backward();
      p.acc_backward();
      assert(get_dx(p) < 0.0); // Signs should flip
      assert(get_dy(p) < 0.0); // Signs should flip
  }
#endif
```

Notes:
get_dx() and get_dy() are free function to be implemented in player, outside of class.
