### ISSUE TITLE
Before Friday 12:00: suggest time, date, frequency, location

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#2]
I suggest the following time, date, frequency and location:

Before each Keivrijdag (that is, once per two weeks), we'll work from 17:00-19:00 at Franjo's fancy library (580) in the Linnaeusborg.

**Comment by richelbilderbeek** [comment]
Just to be obvious: if there is only one suggestion, voting will be simple :rainbow:

**Comment by swom** [comment]
I agree this could be our usual meeting time, in case of extensive absence of group members we can have  a B-meeting day, like on Tuesday at 17pm like we did last time?

**Comment by Neves-P** [comment]
Agreed!

**Comment by boman0815** [comment]
also in for the brainstorming early next week.
for the regular meeting id suggest another day than friday, since i cant make it everytime. anyways if im not the physically, its also fine. 
id suggests thursdays 17-19, every week or second.

**Comment by joshwlambert** [comment]
I like Friday at 17pm, on Keivrijdag days.

**Comment by richelbilderbeek** [comment]
Suggestions are in:

 * Before each Keivrijdag (that is, once per two weeks), from 17:00-19:00 at Franjo's fancy library (580) in the Linnaeusborg.
 *  Weekly, Thursdays 17:00-19:00
 *  Every two weeks, Thursdays 17:00-19:00
