### ISSUE TITLE
Create a player_state enum class

### ISSUE THREAD

**Issue by swom** [tresinformal/game#213]
Let's first create a class that helps us represent the different states the player can be in.

Create  the `player_state.h` and `player_state.cpp` files, and write an enum class called `player_state`:

```c++
enum class player_state
{
  // states the player can be in here 
};
```
You can look at how a enum_class is created in food_type.h or player_shape.h or action_type.h.

Implement player_state so that the following test passes:

```c++
void test_player_state()
{
  assert(player_state::active != player_state::stunned);
}
```
Note: you need to copy paste this test in the code the test yourself, you will not find it already in the code. Try to figure out where it should go.

**Comment by ollyturner** [comment]
😃

**Comment by ollyturner** [comment]
Thank you

**Comment by swom** [comment]
First issue of a series...

**Comment by ollyturner** [comment]
Haha yes!!!

**Comment by ollyturner** [comment]
With this we can go on to make more states.
