### ISSUE TITLE
Create game_view.pri

### ISSUE THREAD

**Issue by swom** [tresinformal/game#215]
@richelbilderbeek why instead of using the pragma #LOGIC_ONLY we do not create a separate .pri file for the code necessary for visualization? I think these pragmas do not go well with all compilers, and in general it is just less files to work through if we want to work just on the logic of the game. Another plus is that this will reinforce the controller-logic-visualization framework. Would you agree? I can take care of it.

**Comment by richelbilderbeek** [comment]
I enjoy that initiative! Go ahead and make it come true. 

I do think I added `LOGIC_ONLY` for a good reason, so expect to experience that good reason :sunglasses: :+1:
