### ISSUE TITLE
[PRS][mathematics] 'calc_hue': convert RGB values to hue

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#229]
The game has paper-rock-scissors dynamics, except it uses colors instead of paper, rock and scissors.
When two players touch, the color of the players determines the winner.
Instead of comparing RGB values (i.e. a 3-dimensional value) to determine the winner, one can use the color hue (i.e. a 1-dimensional value). Write the function `calc_hue` that calculates the hue of an RGB color.
Tip: use http://www.niwa.nu/2013/05/math-behind-colorspace-conversions-rgb-hsl/

```c++
  //#define FIX_ISSUE_229
  #ifdef FIX_ISSUE_229
  // Colors have the correct hues
  // See http://www.niwa.nu/2013/05/math-behind-colorspace-conversions-rgb-hsl/
  {
    const color red = create_red_color();
    assert(calc_hue(red) == 0.0);
  }
  {
    const color green = create_green_color();
    assert(calc_hue(red) == 120.0);
  }
  {
    const color blue = create_blue_color();
    assert(calc_hue(blue) == 240.0);
  }
  #endif // FIX_ISSUE_229
```

**Comment by TheoPannetier** [comment]
solved
