### ISSUE TITLE
Add 'get_nth_player_size'

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#235]
Currently, we can get a player's size.

However, to get the size of the nth player within a game, one needs `g.get_player(i).get_size()`. A more natural way would be `get_nth_player_size(g, i)`. 

Make the following test come true:

```c++
  #ifdef FIX_ISSUE_235
  // Can get a player's size by using a free function
  {
    const game g;
    const int n_players{static_cast<int>(g.get_v_player().size())}
    for (int i = 0; i != n_players; ++i)
    {
      const double a{g.get_player(i).get_size()};
      const double b{get_nth_player_size(g, i)};
      assert(std::abs(b - a) < 0.0001);
    }
  }
  #endif // FIX_ISSUE_235
```

This should be easy: all the free function `get_nth_player_size(g, i)` needs to do is call `g.get_player(i).get_size()`. Or: it is just a different way to do the same, without adding anything new/fancy.

**Comment by TheoPannetier** [comment]
> Currently, we can get a player's size.

Are you sure? I can't find 'get.size()', am I missing something?

**Comment by richelbilderbeek** [comment]
I checked to be sure. Yes, it is called [get_diameter](https://github.com/tresinformal/game/blob/develop/player.h#L58) :-)

**Comment by TheoPannetier** [comment]
Fixed!
