### ISSUE TITLE
[FD] The game can be checked for any collision between food and players

### ISSUE THREAD

**Issue by swom** [tresinformal/game#238]
Depends on:
- [ ] #247 
The following test should pass in game.cpp

We need this for testing in #238

```c++
// #define FIX_ISSUE_238
#ifdef FIX_ISSUE_238
  // The game can be checked for any collision between food and players
  {
    game g;
    assert(!any_player_food_collision(g));
    put_player_on_food(g.get_player(0), g.get_food()[0]);
    assert(any_player_food_collision(g));
  }
#endif
```

**Comment by TheoPannetier** [comment]
Sounds a lot like a duplicate issue of #247...
Though I understand the goal here is to check if there is ANY collision between food and players in the entire game, to be used as an assert in #254.
I'll try to rephrase the test

**Comment by TheoPannetier** [comment]
Done!
