### ISSUE TITLE
Vote: allow outsider adults Yes/No?

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#24]
There are some adults interested in joining the `tresinformal` team. Does the team think it is a good idea to allow them?

I suggest to vote, with a 2/3 majority of 'Yes' needed to allow them to join.

**Comment by AparajithaRamesh** [comment]
Yes

**Comment by richelbilderbeek** [comment]
@swom says Yes.

**Comment by richelbilderbeek** [comment]
Whole team: yes
