### ISSUE TITLE
[FD] A player and uneaten food can be checked for collision

### ISSUE THREAD

**Issue by swom** [tresinformal/game#247]
Depends on 
- [x] #237 
The following test should pass in game.cpp:
```c++

//Other tests

#ifdef FIX_ISSUE_247
  {
    player p;
    food f;
    assert(!in_contact_with_uneaten_food(p,f));
    put_player_on_food(p,f);
    assert(in_contact_with_uneaten_food(p,f));

  }
#endif
```

**Comment by TheoPannetier** [comment]
Hold on @swom is this issue a duplicate of #237 ?
To me it looks like `have_same_position(player, food)` and `player_and_food_are_colliding` do the exact same thing.
Should I replace calls to the latter with the former?

**Comment by TheoPannetier** [comment]
Aaaah, got it from #256, you want a function that checks that a player and an **uneaten** food item have the same position

**Comment by TheoPannetier** [comment]
Done!
