### ISSUE TITLE
Volunteers wanted: assist at git and GitHub workshop at conference

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#249]
I will be giving a workshop on git and GitHub on the academic conference [NLSEB PhD and Postdoc Day](http://nlseb.nl/nlseb2021-phd-postdoc-meeting/) workshop, about online collaboration using git and GitHub

During the workshop, things will go wrong for some people. To lead the workshop, I cannot get involved in details. Ask for some volunteers to assist if needed.

 * When: Monday April 19 2021 10.45 - 12.15 in Workshop session I
 * Where: Zoom (link will be here when known)
 * Costs: none, it is a free conference

Who can and wants to be available from 10.30 - 12.30? Beer can be arranged!

Volunteers:

 * Willy: ?Windows
 * Theo: Mac
 * ?: Linux

**Comment by FrieseWoudloper** [comment]
Count me in!

**Comment by TheoPannetier** [comment]
Happy to help!

**Comment by TheoPannetier** [comment]
The workshop occurred, time to close.
It was great fun, thanks both!
