### ISSUE TITLE
[FD] Food items can be randomly placed in the game 

### ISSUE THREAD

**Issue by swom** [tresinformal/game#250]
Depends on:
- [x] #285 
- [x] #400 

The following test should pass in game.cpp:
```c++
// #define FIX_ISSUE_250
#ifdef FIX_ISSUE_250
  //Food can be placed at a random location
  {

    game g;
    std::vector<double> food_x;
    std::vector<double> food_y;

    int repeats = 1000;

    for(int i = 0; i != repeats; i++)
      {
        place_nth_food_randomly(g,0);
        food_x.push_back(get_nth_food_x(g,0));
        food_y.push_back(get_nth_food_y(g,0));
      }
    auto mean_x = calc_mean(food_x);
    auto mean_y = calc_mean(food_y);

    // Mean position of food items should be center of game environment
    double expected_mean_x = (get_max_x(g) + get_min_x(g)) / 2.0;
    double expected_mean_y = (get_max_y(g) + get_min_y(g)) / 2.0;
    double d_mean_x = abs(expected_mean_x - mean_x);
    double d_mean_y = abs(expected_mean_y - mean_y);

    assert(d_mean_x < 0.01);
    assert(d_mean_x < 0.01);

    auto var_x = calc_var(food_x, mean_x);
    auto var_y = calc_var(food_y, mean_y);

    assert(var_x > 0.01);
    assert(var_y > 0.01);
  }
#endif
```

**Comment by TheoPannetier** [comment]
Hey @swom I'm probably ;issing something but shouldn't the conditions in assert be different?
Mean coord == 0 and var coord == 0 can only be obtained with a vector of food items that all have position (0,0). 
Doesn't sound like random placement to me 😉

**Comment by richelbilderbeek** [comment]
I unassiged Gina, as she left the team for now :-)

**Comment by TheoPannetier** [comment]
@kausmees I don't think the test needs to be changed. From what I can see the numbers sampled by `place_randomly()` are always the same, maybe because the RNG is generated inside the function and so reset at every call.
I tried passing the game's seed (through `g.get_rng()`) but that did not fix the issue...

**Comment by richelbilderbeek** [comment]
Me and Theo simplified the test quite a lot! Good stuff!

**Comment by TheoPannetier** [comment]
Done 😎
