### ISSUE TITLE
Functions must return `std::string` instead of `const std::string`

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#262]
Since move semantics, returning a `const std::string` is recommended against, according to [F.15: Prefer simple and conventional ways of passing information](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#f15-prefer-simple-and-conventional-ways-of-passing-information) where the return type is `X` (and not `const X`).

For example:

```c++
const std::string to_str(action_type this_action_type);
```

Should nowadays be:

```c++
std::string to_str(action_type this_action_type);
```

Look in the code for `const std::string` being returned and fix that. This needs to be done in both the .h file and the .cpp file.

**Comment by richelbilderbeek** [comment]
I re-open, as I found another example. Good lucking finding it :+1:

**Comment by richelbilderbeek** [comment]
I have unassigned Xiaoyan, as she has been kept occupied by work for too long now :-). If she gets back to us one day, she can assign herself again :-)

**Comment by richelbilderbeek** [comment]
As of today, there is one in `shelter.h`. Please fix :rainbow:

**Comment by ollyturner** [comment]
sure

**Comment by kausmees** [comment]
Has been done.
