### ISSUE TITLE
Add text to the menu buttons

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#266]
When running the game from menu, as this ...

![Screenshot from 2021-04-14 16-47-22](https://user-images.githubusercontent.com/2098230/114730376-1a067d00-9d41-11eb-9e2d-827433346a17.png)

The game displays a menu as such:

![Screenshot from 2021-04-14 16-47-02](https://user-images.githubusercontent.com/2098230/114730371-18d55000-9d41-11eb-9c24-c59e0ebee7e9.png)

Add text to the buttons, similar to 'Start', 'Options' and 'Quit'

**Comment by Clemcarle** [comment]
@swom , Richel has said to defer this issue to you as you are the "sfml guy" (apparently). 
So here's current progress: everything seems to have been implemented to print the text, except it doesn't actually appear. We have tried several fixes (it's not under the buttons, it's not out of the window frame, it's not black on black, it's not being wrongfully targeted by a destructor) but nothing works. We do not know the source of the issue.

**Comment by Clemcarle** [comment]
[this is going on on the clem branch]

**Comment by richelbilderbeek** [comment]
Yes, @swom is the SFML guy here :-)

@swom: I took a look and I can get the text to be drawn as dots on the **clem** branch. I predict a close look at `void menu_view::draw_buttons() noexcept` by you will solve this problem in minutes!

![Screenshot from 2021-09-08 18-46-21](https://user-images.githubusercontent.com/2098230/132550914-5268e59d-73e8-4e69-9602-aa2aac4154db.png)

**Comment by richelbilderbeek** [comment]
Now with scale 2.0:

![Screenshot from 2021-09-08 18-54-39](https://user-images.githubusercontent.com/2098230/132551992-6520d721-7e77-4d85-a45c-f94a5586d134.png)

**Comment by ollyturner** [comment]
When I run it with @richelbilderbeek's lovely code I don't see the dots:

![image](https://user-images.githubusercontent.com/46792585/132552409-c6da7060-65fc-4cf8-8b91-1944cbf45de8.png)

**Comment by swom** [comment]
Ok guys after months I finally look at the project page again and I find a nice juicy mystery awaiting. I will crack the case.

**Comment by swom** [comment]
Eventually...
