### ISSUE TITLE
Extra optional informal meeting this Saturday

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#29]
Hi team,

For those interested, I'd be up for an extra informal meeting this Saturday, say from 18:00 onwards, at my place. I probably also invite [my hackerspace](https://hive5.nl/). 

Schedule:

 * 18:00: Door open
 * 18:30: Order pizza
 * 22:00: Door closes, unless something awesome replaces this and/or we go someplace else

**Comment by Neves-P** [comment]
Can't join tomorrow, sorry! Have fun 😃

**Comment by swom** [comment]
Sry Richel just saw it now!
I should have checked my github dammit!

**Comment by richelbilderbeek** [comment]
No worries. It was an insightful evening, thanks to Hive5 member @sandervankasteel.
