### ISSUE TITLE
Suggest: what kind of game will we make?

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#3]

**Comment by richelbilderbeek** [comment]
For next Real Life meeting, we will:

 * Allow each team member to share his/her idea, 3 minutes max
 * Vote
 * Make the game with the most votes

**Comment by richelbilderbeek** [comment]
Team members can present their idea (3 minutes max!) at the next Real-Life Meeting, see [Short-Term Schedule](https://github.com/tresinformal/game#short-term-schedule).

**Comment by boman0815** [comment]
here some videos of one screen multiplayer games, that are on general relatively simple, but as stefano pointed out: gain there complexity by competing or cooperating with other players. 

the classic super bomberman
https://www.youtube.com/watch?v=2fuhrwJQ-mQ

the last one i played inversus, which also has a great arcade single player
https://www.youtube.com/watch?v=VN9LW43HG9U

here an example of a basically one screen coop multiplayer game about cooking, could als be done in 2d.
https://www.youtube.com/watch?v=H0GUWPvaHSU

here another idea for a coop game, not one screen anymore. still pretty simple but fun concepts
https://www.youtube.com/watch?v=bNasTnxmabs&list=PLQT9JnNAECySJeTeLXJoepkfkChcSJG0i

**Comment by swom** [comment]
Hey guys, 

As promised here a few links I find might be good to struck some inspiration.
 
This are related to an yearly game jam session organized by a youtuber I follow. I think the games that came out of them can be a very good starting point for us, they are relatively simple, but have all a great single idea behind them. 
Maybe we will not pull one off in 48hrs, but I think it might be reasonable to manage to do something similar (to some of them) with a few months of work!

I will put a link to the video commentary about the best games of each jam session for the last three years, and the website where you can play the games themselves! You can find the top 20 picks of each session in the youtube video description, enjoy:

Year | Commentary | Games
--|--|--
2017 | https://www.youtube.com/watch?v=yDmjt-UfybM | https://itch.io/jam/gmtk-jam/entries
2018 | https://www.youtube.com/watch?v=s2ebZXQ_J8Q | https://itch.io/jam/gmtk-2018/entries
2019 | https://www.youtube.com/watch?v=o-WrQ77zUvA | https://itch.io/jam/gmtk-2019/entries

**Comment by swom** [comment]
Also another game that inspired me deeply, a game about making games:
[The Beginner's guide](https://www.youtube.com/watch?v=RBK5Jheu0To)

I have it on my computer as well so if anyone wants I can give it to you.
From the same creator I also highly recommend:
[The Stanley parable](https://www.youtube.com/watch?v=fBtX0S2J32Y)

**Comment by richelbilderbeek** [comment]
It's been decided by vote, in #15. It's in the README.
