### ISSUE TITLE
Remove useless setters

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#301]
depends on 

- [x] #321

We have more public setters in our interface than justified.

For example, the player class has a member variable called `m_ID` that can be set. This is unexpected: an ID (like a personal number) remains constant, so it is ideally set at construction, after which it can only be read.

Our code, currently, does not handle it like this, e.g here is a test that sets the ID:

```c++
  {
        std::string ID = "1";
        player p;
        p.set_ID(ID);
        assert(p.get_ID() == ID);
  }
```

The reason for the setter is simple: using the constructor would be awkward:

```c++
  {
    const std::string id = "31415";
    const player p(
      0.0,
      0.0,
      player_shape::rocket,
      player_state::active,
      2,
      0.1,
      -0.001,
      -0.1,
      100.0,
      0.01,
      color(),
      id
    );
    assert(p.get_ID() == id);
  }
```

Note that this test would pass :-)

There are two ways to remove the use of `set_id`:

 * Write creator functions, such as `create_player_with_id()`

```c++
  {
    const std::string id = "31415";
    const player p = create_player_with_id(id);
    assert(p.get_ID() == id);
  }
```

 * Write a factory class, such as `player_factory`:

```c++
  {
    const std::string id = "31415";
    player_factory f;
    f.set_id(id);
    const player p = f.create();
    assert(p.get_ID() == id);
  }
```

Decide yourself which options are best. Note that the two ways are in synergy, e.g.

```c++
player create_player_with_id(const std::string& id)
{
    player_factory f;
    f.set_id(id);
    return f.create();
}
```

Also, ideally, `player::m_id` would be read-only and/or const. That is another Issue :-)

**Comment by ollyturner** [comment]
This has already been done:
```
 {
    const std::string id = "31415";
    const player p = create_player_with_id(id);
    assert(p.get_ID() == id);
  }
```
