### ISSUE TITLE
Create read_only template class

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#302]
Currently, some classes have member variables that are read-only, but can be changed anyways, e.g `player::m_id`.

Ideally, as a player's ID cannot change during its existence (same as your personal number and to a lesser extent your name and DNA), this should be reflected in the code.

Write, in files `read_only.h` and `read_only.cpp`:

 * a template class called `read_only` (use our `optional` template class for inspiration)
 * its tests, make sure these are ran

Below are some tests, make all come of these come true:

```c++
read_only<int> x(314); // Can only determine value at construction
assert(x.get() == 314); // Can only get, not set
read_only<int> x_again = x; // Can copy
assert(x.get() == x_again.get());
assert(x == x_again); // Can compare for equality
read_only<int> x_other(271);
assert(x != x_other); // Can compare for inequality
assert(x > x_other);  // Can compare
assert(x >= x_other); // Can compare
assert(x_other < x);  // Can compare
assert(x_other <= x); // Can compare

read_only<double> y(3.14);
assert(y.get() == 3.14);

read_only<std::string> s("pi");
assert(s.get() == "pi");
```

**Comment by TheoPannetier** [comment]
Done 😀
