### ISSUE TITLE
Write 'get_random_game_options'

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#303]
* Needed for #246

The `game_options` class contains all the game options, i.e. those setting you normally set in an 'Options' screen. One set of options are the key-action maps (KAMs), as determined by the key configuration, i.e. which key corresponds to which action.

For testing, we need random `game_options`, especially with random KAMs, as this forces use to work with any random setup, e.g. we can check if a player actually moves forward when pressing its 'go forward' key.

Make the following tests pass:

```c++
  #ifdef FIX_ISSUE_303
  // Two random game options are the same, when the same seed is used
  {
    const int rng_seed = 271;
    const game_options a = get_random_game_options(rng_seed);
    const game_options b = get_random_game_options(rng_seed);
    assert(a == b);
  }
  // Two random game options differ in general
  {
    const int rng_seed = 314;
    const game_options a = get_random_game_options(rng_seed);
    const game_options b = get_random_game_options(rng_seed + 1);
    assert(a != b);
  }
  // Two random game options differ in their key-action maps especially
  {
    const game_options a = get_random_game_options(rng_seed);
    const game_options b = get_random_game_options(rng_seed + 1);
    assert(a.get_kam_1() != b.get_kam_1());
    assert(a.get_kam_2() != b.get_kam_2());
  }
  //#endif // FIX_ISSUE_303
```

The RNG seed is used to initialize a **local** RNG engine, such as a `std::default_random_engine` as used in the `game` class. No need to get fancy and re-use the `game`'s RNG engine.

**Comment by TheoPannetier** [comment]
Make these issues before closing:
- [ ] make sure that `get_random_game_options()` doesn't draw the same keys for two players
- [ ] pass the rng to the `game_options` class

**Comment by TheoPannetier** [comment]
solved
