### ISSUE TITLE
Write 'get_stun_key'

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#304]
Currently, a player has a key-action-map (KAM) that connects a key to an action. For example, for player 1, the key `sf::Keyboard::Num1` is connected to `action::stun`, so that means that when player 1 presses '1', it will shoot a stun rocket. 

For #246 we need an easy way to get the key to shoot a stun rocket. Sure, we can get it from the KAM locally, but we can also make a helper function, called `get_stun_key`. Make the following test come true:

```c++
    #ifdef FIX_ISSUE_304
    //Get the stun key
    {
        const key_action_map m = get_player_1_kam();
        assert(get_stun_key(m) == sf::Keyboard::Num1);
    }
    #endif // FIX_ISSUE_304
```

**Protip:** read the comment thread for a shortcut 😉

**Comment by TheoPannetier** [comment]
This has been (accidentally 😇) solved with #355, one can now call `m.to_key(action_type::shoot_stun_rocket)` to get the desired result.

That being said, defining a wrapper `get_stun_key()` around the line above would make a great `first` issue 🤔

**Comment by ollyturner** [comment]
you were right solved

**Comment by TheoPannetier** [comment]
Done!
