### ISSUE TITLE
Evaluate

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#319]
We can assume we are all awesome, but there is only one way to measure this: an anonymous evaluation!

It must be

 * Anonymous
 * Useful
 * Short

Topic|Tops: good things that should be kept|Tips: things that can be improved
---|---|---
Social| | 
Workflow| | 
Discord| | 
Pavel| | 
Richel| | 
Stefano| | 
[Other team members that want]| |

**Comment by richelbilderbeek** [comment]
Will share with team today at 18:15

**Comment by richelbilderbeek** [comment]
```
Social: tops: what are good things that should be kept?
Social: tips: what are thing that can be improved?
Workflow: tops: what are good things that should be kept?
Workflow: tips: what are thing that can be improved?
Discord: tops: what are good things that should be kept?
Discord: tips: what are thing that can be improved?
Pavel: tops: what are good things that he shoul keep doing?
Pavel: tips: what are thing that he can improve?
Richel: tops: what are good things that he shoul keep doing?
Richel: tips: what are thing that he can improve?
Stefano: tops: what are good things that he shoul keep doing?
Stefano: tips: what are thing that he can improve?
```

**Comment by richelbilderbeek** [comment]
Evaluation will be closed today at approx 19:15. Then I will ask @alexindewit to anonimize the anonymous results even further

**Comment by TheoPannetier** [comment]
Sorry if I missed the info, where do we post evaluations?

**Comment by richelbilderbeek** [comment]
@TheoPannetier evaluation form is at  https://forms.gle/1NZizk5vAcnWUxey9

Results will be posted somewhere in this repo. If there is a problem, please let me know :+1:

**Comment by richelbilderbeek** [comment]
Done! Results are at [https://github.com/tresinformal/game/tree/richel/doc](https://github.com/tresinformal/game/tree/richel/doc)
