### ISSUE TITLE
food equality not working correctly

### ISSUE THREAD

**Issue by pohaha** [tresinformal/game#341]
as of now the equality operation can be performed on food objects
but it does not work as intended:
foods that are on the same coordinate point but with different colour ARE equal, when this is not true in practice.
to fix this issue the following test should pass:
```c++
#ifdef FIX_ISSUE_341
    {
      const food test_food_one(0.0f,0.0f,color());
      const food test_food_two(0.0f,0.0f,color(0,0,0));
      assert(not (test_food_one==test_food_two));
    }
```

**Comment by Yangshen0325** [comment]
We confirmed it is working. We close the issue now.
