### ISSUE TITLE
Adapt 'Coordinate' to coding standard

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#350]
The `Coordinate` class is a useful class for coordinates. Unlike all other classes, e.g `food`, `game`, `enemy`, etc, its name starts with an uppercase. We should [NL.8: Use a consistent naming style](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rl-name).

To do so, rename the class `Coordinate` to `coordinate`

Tip: use CTRL+SHIFT+R to 'Rename symbol under cursor' to do this all at once.

![1](https://user-images.githubusercontent.com/2098230/124799132-82d24f80-df54-11eb-90a8-09f14dc50841.png)

**Comment by TheoPannetier** [comment]
Sorry, we ~accidentally solved this as part of #358
Happy to reverse it if we have a shortage of `first` issue!
