### ISSUE TITLE
Dragons Go Backwards

### ISSUE THREAD

**Issue by ollyturner** [tresinformal/game#361]
The dragons fly where their tails are pointing.

**Comment by TheoPannetier** [comment]
I believe this is not the case, only on your computer. Can't confirm now, I don't have Qt on the one I'm using rn. Anyone?
I have run into the same issue in the past, Qt or the compiler does not update the sprites at some point. I vaguely remember you have to delete some folder to fix this? @richelbilderbeek ?

**Comment by richelbilderbeek** [comment]
I confirm here with a video that the dragons go forward in my omputer:

https://user-images.githubusercontent.com/2098230/132197991-ad6ec5f2-23de-4a6a-90e7-37c4f1e2c05d.mp4

@TheoPannetier : to get the latest and greatest spires, delete the `build-game-Desktop-Debug` folder, which is a sister folder of `game`

**Comment by richelbilderbeek** [comment]
I remov the 'High' label, as it does not affect progress of other Issues,

**Comment by ollyturner** [comment]
@richelbilderbeek fix worked
