### ISSUE TITLE
Add 'shrink' and 'grow' sound_type and sound

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#379]
Currently, the dragons can shrink and grow. These two events should each have their own sound

- [x]  Add these two sound types to `sound_type`

- [x]  Add these two sound types to `to_str` (in `sound_type.cpp`) as well and test these

- [x]  Find two appropriate free (as in freedom) sounds, as @sebmader for sources

- [x] Add member functions to `game_resources` to return a resource

Next step will be to actually play these :-)

**Comment by TheoPannetier** [comment]
I believe this is done, actually!
