### ISSUE TITLE
All classes that have a position now get that position from free logistic functions and not member functions.

### ISSUE THREAD

**Issue by swom** [tresinformal/game#411]
For classes:
- [ ] #416
- [ ] #415
- [ ] #414
- [ ] #413
- [ ] #412

Change all calls to member functions that read the  `m_x `or `m_y `member, i.e.:
```c++
a_class.get_x(); //or
a_class.get_y();
```
to free logistic functions, i.e.:
 ```c++
get_x(const a_class& a_class);
get_y(const a_class& a_class);
```
do this  in both tests and the code. 
The only functions allowed to call member functions to read x and y 
```c++
a_class.get_x(); //or
a_class.get_y();
```
are the free logistic functions you will have used everywhere else
 ```c++
get_x(const a_class& a_class);
get_y(const a_class& a_class);
```

### **To be noted**:

1. If a free_logistic function with the same name exists for the class **_DO NOT_** write a new one, or change the existing one, just swap it with calls to the member function.
2. you **_SHALL NOT_** delete the definition and declaration of 
```c++
a_class.get_x(); //or
a_class.get_y();
```
from a class, keep it, just do not let anybody except the free logistic functions use it.

**Comment by TheoPannetier** [comment]
Would a template be a good idea here? I'm tempted to take advantage of the 'get_position()' function that all items share and do it all at once with 

```cpp
template <typename T>
double get_x(const T& item)
{ 
    return item.get_position.get_x();
}
template <typename T>
double  get_y(const T& item)
{ 
    return item.get_position.get_y();
}
```

or is some good ol' function overloading preferable?

**Comment by richelbilderbeek** [comment]
@TheoPannetier: this is a fun idea and I am happy you found it (and I could not help fix the code).  

I would not mind gradually adding this to the project. It would be a good experience for some team members to experiment with templates. 

Argument against doing so, is that no new functionality is gained (just existing one removed) and the code will be harder for newbies to understand. 

I think with the current state of the team, I think the pros outweight the cons :-)

```c++
template <typename T>
double get_position(const T& item)
{ 
    return item.get_position();
}
template <typename T>
double get_x(const T& item)
{ 
    return get_position(item).get_x();
}
template <typename T>
double  get_y(const T& item)
{ 
    return get_position(item).get_y();
}
```
