### ISSUE TITLE
A game has an enemy

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#42]
Our game needs one enemy (for starters).

 * Create a class called `enemy`, put it in files `enemy.h` and `enemy.cpp`
 * An enemy has member functions `get_x` (to get its x coordinat) and `get_y` (to get its y coordinat)
 * By default, the enemy's coordinat is (0,0)
 * Write a test called `test_enemy` in the same files
 * Add that test to the test suite in the `test` function in `main.cpp`

**Comment by joshwlambert** [comment]
Completed.
