### ISSUE TITLE
Environment should use coordinates instead of x and y

### ISSUE THREAD

**Issue by swom** [tresinformal/game#426]
Depends on 

- [x] #424 

In enviornment.h:

- [ ] Remove memeber functions get_x and get_y
- [ ] Remove the memeber variables m_x and m_y
- [ ]  and (if not done for #424) add member variables
```c++
coordinate m_top_left;
coordinate m_bottom_right;
```
- [ ] (if not done for #424) repurpose member functions
```c++
const coordinate& get_top_left() const noexcept
const coordinate& get_bottom_right() const noexcept
```
to work with the coordinate new `coordinate` members
- [ ] create free functions `get_max_`x/y`(const environmnet& e)` and `get_min_`x/y`(const environmnet& e)`.

**Comment by TheoPannetier** [comment]
There are no `get_x()` / `get_y()` or `m_x`, `m_y` in `environment` so solved I guess 👍
