### ISSUE TITLE
Move ideas to README.md

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#437]
Now the Issues labeled 'Idea' clog up the Issues ...

![Screenshot from 2021-11-24 17-25-15](https://user-images.githubusercontent.com/2098230/143276659-4ff02932-8843-4c96-893d-3814047dfb27.png)

... suggesting we have more open Issues than we actually have. 

The idea (no pun intended) was to have some kind of roadmap of Idea Issues, but I feel this has gone stale, and now the cost of having the Idea Issues outweighs their benefits.

I suggest to move these to the README.md, after asking @TheoPannetier, as he knows the Issues best :-)

@TheoPannetier, do you agree yes/no?

**Comment by TheoPannetier** [comment]
Definitely agree, ideas issues feel awkward as issues (when should they be closed?). Since we don't use them for anything more than guidelines, maybe a bullet point list in `readme.md` would be more fitting indeed.

**Comment by richelbilderbeek** [comment]
Cool, thanks @TheoPannetier, with your blessing, let's do this! I will probably do this this evening ...

**Comment by richelbilderbeek** [comment]
Renamed the Issue and unassigned for any volunteer to pick up this Issue :-)

**Comment by ollyturner** [comment]
The links in the table aren't working as they bring me to a github page not found

**Comment by ollyturner** [comment]
Fixed ^
          |
