### ISSUE TITLE
The `color` of any player can be accessed easily

### ISSUE THREAD

**Issue by TheoPannetier** [tresinformal/game#457]
To prepare the ground for implementing  changes in the color of players, it would be great to have a free function that helps accessing the color of any given player. Make such a function come to life 🌈 

```cpp
#define FIX_ISSUE_457
#ifdef FIX_ISSUE_457
  {
    // (457) The color of any player can be accessed easily
    game g;
    color color_player_one = get_nth_player_color(g, 0);
    color color_player_two = get_nth_player_color(g, 1);
    color color_player_three = get_nth_player_color(g, 2);
    // Default colors for players: R, G, B
    assert(color_player_one == create_red_color()); 
    assert(color_player_two == create_green_color());    
    assert(color_player_three == create_blue_color());        
  }
#endif
```

**Hint:** if you're stuck, look for existing functions that do similar stuff, e.g. `get_nth_player_size()`

**Comment by swom** [comment]
@ollyturner @Yangshen0325 
Hello guys, I have decided to reassign you to this issue as you had completed it in your previous pull request but in a way that after some consideration I did not consider satisfying. Please try again to solve this issue (merge `develop` on your branch first) _without_ commenting out parts of the test.
Best of luck!
