### ISSUE TITLE
A player has an initial size of 100

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#46]
A player has a size, which can grow or shrink during the game

 * Add a member variable to `player` called `m_size` of type `double`
 * `m_size` should be one hundred upon construction
 * Add a member function called `get_size` that returns the size
 * Make this test pass:

```c++
  #ifdef FIX_ISSUE_46
  // A player has an initial size of one hundred
  {
    const player p{1.2, 3.4, player_shape::rocket};
    assert(std::abs(p.get_size() - 100.0) < 0.00001);
  }
  #endif
```

**Comment by joshwlambert** [comment]
Completed.
