### ISSUE TITLE
Make ready-made black and white colors

### ISSUE THREAD

**Issue by TheoPannetier** [tresinformal/game#460]
The project currently has three functions to call read-made colors, namely:

- `create_red_color()`
- `create_green_color()`
- `create_blue_color()` 

It would be nice to also be able to call ready-made black and white colors. starting from the functions above, make `create_black _color()` and `create_white_color()`.

```cpp
//#define FIX_ISSUE_460
#ifdef FIX_ISSUE_460
  // #460 Ready-made black and white colors are available
  {
    const color black = create_black_color();
    assert(get_redness(black) == 255);
    assert(get_greenness(black) == 255);
    assert(get_blueness(black) == 255);
  }
  {
    const color white = create_white_color();
    assert(get_redness(white) == 0);
    assert(get_greenness(white) == 0);
    assert(get_blueness(white) == 0);
  }
#endif // FIX_ISSUE_460
```

**Comment by Luxwor** [comment]
Added black and white color
