### ISSUE TITLE
[Housekeeping] Move free functions to separate file and header

### ISSUE THREAD

**Issue by TheoPannetier** [tresinformal/game#466]
☁️ :broom:
So far, most (all?) free getter functions like `get_nth_food_color()`, `get_nth_player_size()` etc. are located in `game.cpp`.
While it makes sense to include them there because they all take a `game` as their first argument, they do not belong to the actual class `game` and take up a significant amount of space, along with their tests. It would be great to move them to a separate file (e.g. `free_functions.cpp` or `free_getters.cpp` ?) that also include their tests, so `game.cpp` could be a bit more readable.

**Comment by richelbilderbeek** [comment]
I like this idea! 

I would need to look up the recommended practices here. I feel one big file called `free_functions.h` would only move the problem, as other classes also have free functions. A `game_functions.h` appeals more to me. Again, need to look up in The C++ Core Guidelines!

As you spotted the free functions that take a `game` are there, but they need not be there when we will discuss forward declarations today.

**Comment by TheoPannetier** [comment]
Ok, looking forward to hear about forward declarations 😀
