### ISSUE TITLE
Make code independent of SFML version

### ISSUE THREAD

**Issue by kausmees** [tresinformal/game#474]
With SFML version 2.4, the function sf::Text::SetColor() was deprecated and replaced by other ones, including setFillColor() which is currently used in the code.

(see https://www.sfml-dev.org/documentation/2.4.0/classsf_1_1Text.php)

This causes a build error when using a SFML version < 2.4

Preprocessor directives should be used to handle this so that the build works for SFML versions younger than 2.4.

**Comment by TheoPannetier** [comment]
Done, thanks @kausmees !
