### ISSUE TITLE
Read the code of conduct 

### ISSUE THREAD

**Issue by TheoPannetier** [tresinformal/game#486]
To ensure that `tresinformal` remains a fun and safe environment for everyone, we follow a ![Code of Conduct ](https://github.com/tresinformal/game/blob/master/CODE_OF_CONDUCT.md). 

Assign yourself, read the code, and close when you are done.

This is a recurrent issue, so if nobody is assigned, re-open.

**Comment by janclod** [comment]
done ☮️ ❤️

**Comment by nishamghimire5** [comment]
read

**Comment by nishamghimire5** [comment]
done
