### ISSUE TITLE
Suggest: What to do with Christmas?

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#52]
Some people celebrate their holidays by -ironically- *not* programming. What will we do?

I suggest not to meet during Christmas holidays on December 27th, as I will be absent.

I do suggest to meet on January 3rd, as it's also the first Keivrijdag of the year.

**Comment by swom** [comment]
I agree, i might not be around for a while during the Christmas period. But can always follow from GitHub.

**Comment by richelbilderbeek** [comment]
Let's assume Christmas in no tresinformal and let's see what happens :rainbow:
