### ISSUE TITLE
Do we welcome contributions from non-team members?

### ISSUE THREAD

**Issue by TheoPannetier** [tresinformal/game#549]
In #510, I feel it would be important to explicitly mention whether we would accept contributions from anyone, or if people should first join the team before contributing to issues/code . What policy do we want to set here?

**Comment by EvoLandEco** [comment]
IMO if the project will be more popular in future, it must accept contributions from non-team members, as long as the contributions meet our standard. Also we could try to invite the contributors to join our team.

**Comment by TheoPannetier** [comment]
> it must accept contributions from non-team members, as long as the contributions meet our standard

Yes, that sounds fair indeed! So then it's up to CONTRIBUTING.md to clearly lay out what our standards are :)
I'll keep this in mind when addressing #510
