### ISSUE TITLE
Use 'int' instead of 'unsigned int' or 'short'

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#593]
In the class `scoreboard` there are those fancy datatypes called 'unsigned int' and 'short'. It is recommended to always use `int` (see Scott Meyers, 'Efficient C++' and 'C++ Coding Standards: 101 Rules, Guidelines, and Best Practices' by Sutter & Alexandrescu). 

Reasons are:

 * the one bit does not matter sizewise, 
 * the one bit is actually useful to detect errors
 * using `short` is premature optimization: we do not need to save those couple of bytes

**Comment by richelbilderbeek** [comment]
Hi @EvoLandEco, can I give you this Issue? I feel it would be a good execise :-)

**Comment by EvoLandEco** [comment]
@richelbilderbeek Of course, I'll have a look

**Comment by richelbilderbeek** [comment]
@EvoLandEco  Fun and thanks! We can do this together next week as well of course :-)

**Comment by EvoLandEco** [comment]
Closed by #603
