### ISSUE TITLE
`about` contains a link to join the Discord server

### ISSUE THREAD

**Issue by TheoPannetier** [tresinformal/game#598]
I feel the About screen should offer interested players to join and contribute. This could be done via a "Join" button that links to an invite to the Discord server.

For this, we need `about` to get an invite link, to be passed to `about_view` later on.

```cpp
{
    about ab;
    std::vector<std::string> link_to_discord = ab.get_link_discord();
 }
```

**Comment by Luxwor** [comment]
its proving really dificult

**Comment by OggyOggelito** [comment]
There must be a way to dodge
