### ISSUE TITLE
An options_view allows a user to modify game_options

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#631]
### Context

The options screen (called `options_view`) is a dialog in which the user can specify his/her ideal preferences for the game.
These preferences/settings are encapsulated in `game_options`.
It would make sense that the `options_view` allows one to modify all `game_options`.

In this case, provide for:

 * a `options_view` takes a `game_options` at construction, which will be displayed on screen
 * a `options_view` has an internal `game_options` it works on
 * a `options_view` has an internal `game_options` that can be requested at, for example, when closing the dialog

### Test

 * [x] On `develop`? Not yet

In `options_view.cpp`:

```cpp
  #ifdef FIX_ISSUE_631
  // (631) An options_view allows a user to modify game_options
  {
    const game_options options;
    const options_view view(options);
    const game_options options_again(view.get_options());
    assert(options == options_again);
  }
  #endif // FIX_ISSUE_631
```

**Comment by TheoPannetier** [comment]
Done, pending the next pull request
