### ISSUE TITLE
Draw player at its coordinats

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#70]
Currently, the player is drawn at coordinat (300, 400):

```c++
void game_view::show() noexcept
{
  //...

  //Draw the player
  sf::RectangleShape rect(sf::Vector2f(200.0, 100.0));
  rect.setPosition(300.0, 400.0);
  rect.setRotation(static_cast<float>(m_game.get_player().get_direction()));
  m_window.draw(rect);

  //...
}
```

Replace that coordinat by the player's. coordinat.

If needed, initialize a player at different coordinats.

**Comment by swom** [comment]
Isn't this a bit redundant with issue #92?

**Comment by richelbilderbeek** [comment]
Yup, Apu already spotted it's a duplicate :female_detective:

**Comment by richelbilderbeek** [comment]
Duplicate is done, so this one as well :+1:
