### ISSUE TITLE
Remove `qrc_` files from code coverage

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#73]
Currently, the code coverage profile shows:

![there](https://user-images.githubusercontent.com/2098230/68533928-21954b80-032f-11ea-90d3-c23c887d1572.png)

The files with a box around them are created by Qt, not by us. Because they warp our code coverage, let Travis delete these files before calling `get_code_cov`:

```
  # Get code coverage
  - cp debug/*.* .
  - ./scripts/get_code_cov >/dev/null
```

This *should* be easy. If you run into unexpected compilations, re-assign the Issue to a medior or senior.

**Comment by Neves-P** [comment]
Fixed (hopefully) in c3a7efb
