### ISSUE TITLE
Upload a player sprite with transparency in PNG format

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#76]
Upload a player sprite that is free (as in freedom), has transparency and is in PNG format.

Here is an example sprite:

![example](https://user-images.githubusercontent.com/2098230/68534214-f6f8c200-0331-11ea-80ca-9c1c151b684a.png)

**Comment by Xiaoyan2** [comment]
Should we design our own player or just upload whatever we like (of course free)?

**Comment by richelbilderbeek** [comment]
Both are fine :+1:

**Comment by richelbilderbeek** [comment]
@Xiaoyan2: if you know people interested in graphics, they are welcome to do so for our team :+1:

**Comment by richelbilderbeek** [comment]
I assign @GiorgioBoccarella, as lead graphics. Feel free to re-assign within your team :+1:

**Comment by richelbilderbeek** [comment]
Looks done to me!
