### ISSUE TITLE
OCLint has helpful comments 

### ISSUE THREAD

**Issue by swom** [tresinformal/game#79]
Dear @richelbilderbeek. This time Travis says there are compile errors that will not allow OClint to run. I have not looked into this too much, but on my computer everything runs nice and dandy. It is strange because just before I had pulled everything again and merge and pushed and Travis was happy. Have I made some fatal mistake? I admit I corrected one word in one error output string  from the code you used to exclude the sound from being compiled in Travis, but this seems to me uninfluential to the compiling. Let me know if you can, and sorry for keeping bothering you, I just assume you could fix Travsi issues faster than I could.

**Comment by swom** [comment]
It seems it does not like the test for issue #67

**Comment by richelbilderbeek** [comment]
Hi @swom, I see [in the Travis build log](https://travis-ci.org/tresinformal/game/jobs/610640011#L1219) of your last commit the following advices given by OCLint:

```
/home/travis/build/tresinformal/game/action_type.cpp:5:3: constant conditional operator [basic|P2] 
/home/travis/build/tresinformal/game/action_type.cpp:6:3: constant conditional operator [basic|P2] 
/home/travis/build/tresinformal/game/game.cpp:19:5: covered switch statements dont need default [convention|P3] 
/home/travis/build/tresinformal/game/game.cpp:19:5: missing break in switch statement [convention|P2] 
```

OCLint is right. Try to fix these pieces of advice: it will improve your style.

In case you think OCLint is wrong, use a `//!OCLINT` tag, followed by a reason like this:

```c++
void test() //!OCLINT test functions may be long
{
  // ...
}
```

Note that OCLint usually is right however. Try to find an idiom that makes OCLint happy :+1:

**Comment by richelbilderbeek** [comment]
AFAICS, this is fixed. Closing the Issue :+1:
