### ISSUE TITLE
My complier keeps complaining "unused variable" when I use 'assert'   

### ISSUE THREAD

**Issue by Xiaoyan2** [tresinformal/game#85]
Hi Rachel,
 
May I ask a question about the wired thing that my complier did?

This is a piece of codes from Stefano:

```c++
 {
    const game g;
    const double a{g.get_player().get_direction()};
    const double b{get_player_direction(g)};
    assert(std::abs(b - a) < 0.0001);
   }
```

However, the complier complained that "unused variable a" and "unused variable b" on my laptop.

To solve this problem, I need to define unused (x), and my code shows as below:

```c++
#define _unused(x) (void(x))
{
    const game g;
    const double a{g.get_player().get_direction()};
    const double b{get_player_direction(g)};
    assert(std::abs(b - a) < 0.0001);
    _unused (a);
    _unused(b);
}
```

This could work on my laptop, but how can I use assert normally on my laptop without define?

**Comment by richelbilderbeek** [comment]
I predict you let the compiler compile in release model, as this removes all `asserts` resulting in the compiler messages you received.

Solutions are to compile in debug model, or have less compiler warnings in release model.

Good luck :+1:

**Comment by Xiaoyan2** [comment]
Thanks a lot. It works well now!
