### ISSUE TITLE
Minimal Pi Clock: who wants it?

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#86]
I've made a new Minimal Pi Clock ([pictures here](https://github.com/richelbilderbeek/MinimalPiClock/tree/master/pics/20191117)). For to respond can have it :+1:

**Comment by xieshu95** [comment]
@richelbilderbeek Me! Me! I want it!

**Comment by joshwlambert** [comment]
I'll buy you a beer if I can have it!!

**Comment by richelbilderbeek** [comment]
@xieshu95: It's yours, will bring it tomorrow :rainbow: 

@joshwlambert:  being faster next time will be the superior option :grin:

**Comment by richelbilderbeek** [comment]
@joshwlambert: and there will be a next time, probably this weekend :+1:
