### ISSUE TITLE
Vote: Coding standard 

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#93]
Instead of nitpicking on the number of spaces, or the placement of brackets, we'll vote for a coding style, that follow [the clang-format](https://zed0.co.uk/clang-format-configurator/).

Current candidates:

  1. BreakBeforeBraces: Allman (default indentation of 2 spaces) (this is the standard used by @richelbilderbeek)
  2. BreakBeforeBraces: Allman, indentation of 4 spaces (this is the standard used by @swom)
  3. All default (indentation will be 2, BreakBeforeBraces will be Attach)
  4. Your [clang-format-configurator](https://zed0.co.uk/clang-format-configurator) suggestions, post it as an new comment to this Issue.

Following the principles of the Ruthless Democracy, we'll vote at 18:15 sharp for all options.

**Comment by AparajithaRamesh** [comment]
At 29 November, 2019 at 1715 sharp!!

**Comment by swom** [comment]
For those who do not know what would possibly be the difference: [Indentation_style](url)

**Comment by richelbilderbeek** [comment]
Note to self: The clang format configurator can be found [here](https://zed0.co.uk/clang-format-configurator/).

**Comment by sebmader** [comment]
First option
